version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "12:00"
    commit-message:
      prefix: 👷
  - package-ecosystem: nuget
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "12:00"
    commit-message:
      prefix: ⬆
