name: Build and Test
on:
  pull_request:
    types: [synchronize, opened, edited]
  push:
    branches: [main]
jobs:
  build:
    permissions:
      id-token: write
      checks: read
    strategy:
      matrix:
        cfg: [Release, Debug]
        os: [ubuntu, macos, windows]
        version: ['8.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet format --verify-no-changes
    - name: Build Project
      run: >-
        dotnet build --nologo --no-restore
        --configuration ${{ matrix.cfg }}
    - name: Run Tests
      working-directory: ${{github.workspace}}/Atmosphere.Tests
      run: >-
        dotnet test --nologo --no-restore
        --configuration ${{ matrix.cfg }}
        --logger GitHubActions
        --property:CoverletOutput=${{github.workspace}}/coverage.opencover.xml
    - name: Upload Coverage
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
      with:
        files: ${{github.workspace}}/coverage.opencover.xml
        use_oidc: true
