name: Build and Test
on: push
jobs:
  build:
    strategy:
      matrix:
        cfg: [Release, Debug]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['6.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829 # tag=v2
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet format --verify-no-changes
    - name: Build Project
      run: >-
        dotnet build --nologo --no-restore
        --configuration ${{ matrix.cfg }}
    - name: Run Tests
      working-directory: ${{github.workspace}}/Atmosphere.Tests
      run: >-
        dotnet test --nologo --no-restore
        --configuration ${{ matrix.cfg }}
        --logger "console;verbosity=normal"
