name: Build and Test
on: push
jobs:
  build:
    strategy:
      matrix:
        cfg: [Release, Debug]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['5.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet format --check
    - name: Build Project
      run: >-
        dotnet build --nologo --no-restore
        --configuration ${{ matrix.cfg }}
    - name: Run Tests
      working-directory: ${{github.workspace}}/Atmosphere.Tests
      run: >-
        dotnet test --nologo --no-restore
        --configuration ${{ matrix.cfg }}
        --logger "console;verbosity=normal"
