name: Build and Test
on:
  pull_request:
    types: [synchronize, opened, edited]
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        cfg: [Release, Debug]
        os: [ubuntu, macos, windows]
        version: ['6.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet format --verify-no-changes
    - name: Build Project
      run: >-
        dotnet build --nologo --no-restore
        --configuration ${{ matrix.cfg }}
    - name: Run Tests
      working-directory: ${{github.workspace}}/Atmosphere.Tests
      run: >-
        dotnet test --nologo --no-restore
        --configuration ${{ matrix.cfg }}
        --logger GitHubActions
