name: Build and Test
on: push
jobs:
  build:
    strategy:
      matrix:
        cfg: [Release, Debug]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['6.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0 # tag=v3
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: dotnet restore
    - name: Install Tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet format --verify-no-changes
    - name: Build Project
      run: >-
        dotnet build --nologo --no-restore
        --configuration ${{ matrix.cfg }}
    - name: Run Tests
      working-directory: ${{github.workspace}}/Atmosphere.Tests
      run: >-
        dotnet test --nologo --no-restore
        --configuration ${{ matrix.cfg }}
        --logger "console;verbosity=normal"
