name: Package
on:
  push:
    tags: [v1.*]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['3.1.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration ${{ matrix.cfg }}
      - name: Create Package
        run: >-
          dotnet pack --nologo
          --no-build
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
        id: pack
      - name: Publish Package
        if: matrix.cfg == 'release'
        run: >-
          dotnet nuget push --nologo
          --force-english-output
          --skip-duplicate
          --api-key ${{secrets.PWSH_TOKEN}}
          --source https://www.powershellgallery.com
          --timeout 60
          ${{steps.pack.outputs.package}}
