name: Package
on: push
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Build Project
        run: dotnet build --nologo --configuration ${{ matrix.configuration }}
      - name: Create Package
        run: dotnet pack -p:RepositoryCommit=${{ github.sha }}
