name: Package
on:
  push:
    tags: [v1.*]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['3.1.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0 # tag=v3
        with:
          dotnet-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration ${{ matrix.cfg }}
      - name: Create Package
        run: >-
          dotnet pack --nologo
          --no-build
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
        id: pack
      - name: Publish Package
        if: matrix.cfg == 'release'
        run: >-
          dotnet nuget push --nologo
          --force-english-output
          --skip-duplicate
          --api-key ${{secrets.PWSH_TOKEN}}
          --source https://www.powershellgallery.com
          --timeout 60
          ${{steps.pack.outputs.package}}
