name: Package
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu, macos, windows]
        version: ['6.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
        with:
          dotnet-version: '6.x'
      - name: Create Package
        id: pack
        run: >-
          dotnet pack --nologo
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
      - name: Upload Package Artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: ${{matrix.os}}-${{matrix.cfg}}-${{steps.pack.outputs.package-filename}}
          path: ${{steps.pack.outputs.package-filepath}}
