name: Package
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu, macos, windows]
        version: ['6.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3
        with:
          dotnet-version: '6.x'
      - name: Create Package
        id: pack
        run: >-
          dotnet pack --nologo
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
      - name: Upload Package Artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
        with:
          name: ${{matrix.os}}-${{matrix.cfg}}-${{steps.pack.outputs.package-filename}}
          path: ${{steps.pack.outputs.package-filepath}}
