name: Package
on:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu, macos, windows]
        version: ['6.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3
        with:
          dotnet-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration ${{ matrix.cfg }}
      - name: Create Package
        id: pack
        run: >-
          dotnet pack --nologo
          --no-build
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
      - name: Upload Package Artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}-${{steps.pack.outputs.package-filename}}
          path: ${{steps.pack.outputs.package-filepath}}
      - name: Publish Package
        if: matrix.cfg == 'release' && github.ref_type == 'tag'
        run: >-
          dotnet nuget push --nologo
          --force-english-output
          --skip-duplicate
          --api-key ${{secrets.PWSH_TOKEN}}
          --source https://www.powershellgallery.com
          --timeout 60
          ${{steps.pack.outputs.package-filepath}}
