name: Package
on:
  push:
    tags: [v1.*]
jobs:
  build:
    strategy:
      matrix:
        cfg: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['3.1.x']
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration ${{ matrix.cfg }}
      - name: Create Package
        run: dotnet pack --configuration ${{ matrix.cfg }} --version-suffix ${{ github.sha }}
