name: Package
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        cfg: [debug, release]
        os: [ubuntu, macos, windows]
        version: ['6.x']
    runs-on: ${{ matrix.os }}-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Create Package
        id: pack
        run: >-
          dotnet pack --nologo
          --configuration ${{ matrix.cfg }}
          --version-suffix ${{ github.sha }}
      - name: Upload Package Artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
        with:
          name: ${{matrix.os}}-${{matrix.cfg}}-${{steps.pack.outputs.package-filename}}
          path: ${{steps.pack.outputs.package-filepath}}
